site_name: Saving Willy Code Documentation
dev_addr: 127.0.0.1:8888
theme:
  name: material

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - mkdocs-homepage-copier
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]


nav:
  - README: index.md