site_name: Saving Willy Code Documentation
dev_addr: 127.0.0.1:8888
theme:
  name: material

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - mkdocs-homepage-copier
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]


nav:
  - README: index.md
  - API:
    - Main app: main.md
    - Data entry handling: input_handling.md
    - Whale gallery: whale_gallery.md
    - Whale viewer: whale_viewer.md
    - Map of observations: obs_map.md
    - Logging: st_logs.md
    - Tab-rendering fix (js): fix_tabrender.md



    - Development clutter:
      - Demo app: app.md