site_name: Saving Willy Code Documentation
dev_addr: 127.0.0.1:8888
theme:
  name: material

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - mkdocs-homepage-copier
  - mkdocstrings:
      default_handler: python
      handlers:
        python: 
          paths: [nonexistent_path_on_purpose]


nav:
  - README: index.md
  - Release Protocol: release_protocol.md
  - How to contribute:
    - Dev Notes: dev_notes.md
  - App:
    - Main App & Home Page: home.md
    - Pages: 
      - Overall Notes: pages.md
      - Map Page: pages_map.md
      - Requests Page: pages_requests.md
      - Classifiers Page: pages_classifiers.md
      - Gallery Page: pages_gallery.md
      - Logs: pages_logs.md
    - Modules:
      - Data Entry Handling: 
        - Data Input: input_handling.md
        - Data Extraction & Validation: input_validator.md
        - Data Object Class: input_observation.md
      - Hugging Face Dataset: 
        - Download: dataset_download.md
        - Cleaning: dataset_cleaner.md
        - Push Observations to Dataset: dataset_hf_push_observations.md
        - Data Requests: dataset_requests.md
        - Fake data: dataset_fake_data.md
      - Hugging Face Classifiers: 
        - Cetacean Fluke & Fin Recognition: classifier_image.md
        - (temporary) Hotdog Classifier: classifier_hotdog.md
      - Map of observations: obs_map.md
      - Whale gallery: whale_gallery.md
      - Whale viewer: whale_viewer.md
      - Logging: st_logs.md
      - Utils: 
        - Tab-rendering fix (js): utils_fix_tabrender.md
        - Metadata handling: utils_metadata_handler.md
        - Grid maker: utils_grid_maker.md

    - Development clutter:
      - Demo app: app.md
