site_name: Saving Willy Code Documentation
dev_addr: 127.0.0.1:8888
theme:
  name: material

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - mkdocs-homepage-copier
  - mkdocstrings:
      default_handler: python
      handlers:
        python: 
          paths: [nonexistent_path_on_purpose]


nav:
  - README: index.md
  #- Quickstart:
    #- Installation: installation.md
    #- Usage: usage.md
  - API:
    - Main app: main.md
    - Modules:
      - Data entry handling: 
        - Data input: input_handling.md
        - Data extraction and validation: input_validator.md
        - Data Object Class: input_observation.md
      - Classifiers: 
        - Cetacean Fluke & Fin Recognition: classifier_image.md
        - (temporary) Hotdog Classifier: hotdog.md
      - Hugging Face Integration: 
        - Push Observations to Dataset: hf_push_observations.md
      - Map of observations: obs_map.md
      - Whale gallery: whale_gallery.md
      - Whale viewer: whale_viewer.md
      - Logging: st_logs.md
      - Utils: 
        - Tab-rendering fix (js): fix_tabrender.md
        - Metadata handling: metadata_handler.md
        - Grid maker: grid_maker.md

    - Development clutter:
      - Demo app: app.md
    
  - How to contribute:
    - Dev Notes: dev_notes.md
