name: Sync to Hugging Face hub DEV
on:
  push:
    branches: [dev]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "*.png"
          git add .gitattributes
          git add src/images/design/challenge1.png src/images/design/challenge2.png src/images/design/leaderboard.png
          git commit -m "Track images with Git LFS" || echo "No changes to commit"
      - name: Push to DEV hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{secrets.HF_USERNAME}}
        run: git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/Saving-Willy/saving-willy-dev dev:main